#ifndef _GRAPHICS_H_
#define _GRAPHICS_H_

#define SET_VBE_MODE 0X4F02
#define RETURN_VBE_MODE 0x4F01
#define RETURN_VBE_CONTROLLER_INFO 0x4F00

#define BIOS_VIDEO_SERVICES 0x10

#define VALID_FUNC 0x4F
#define SUCCESS_FUNC 0x00

#endif
